import { SaveData } from './types';

import {
  BIOMES,
  BIOME_SCENE_PROFILES,
  GAME_ASSET_MANIFEST,
  HAZARD_BEHAVIOR_REGISTRY,
  INTRO_STORY_SEQUENCE,
  LEVELS,
  LEVEL_AUDIO_PROFILES,
  MAP_REGIONS,
  REWARD_PATTERN_REGISTRY,
  ROUTE_SCRIPTS,
  SHOP_ITEMS,
  THEME_PROFILES,
} from './content';
import { SAVE_DATA_VERSION } from './engine/config';

export const DEFAULT_SAVE: SaveData = {
  version: SAVE_DATA_VERSION,
  totalTokens: 0,
  highScore: 0,
  maxLevelReached: 1,
  skins: ['default'],
  equippedSkin: 'default',
  ropeTypes: ['vine'],
  equippedRopeType: 'vine',
  hasCompletedStoryIntro: false,
  selectedMoodPreset: 'Balanced',
  customSwingLabConfig: null,
  achievements: [],
  runHistory: [],
  lastSelectedLevelId: 1,
  settings: {
    masterVolume: 1,
    musicVolume: 1,
    sfxVolume: 1,
    hudDensity: 'full',
    motionIntensity: 'full',
    mapClarity: 0.72,
    visualDensity: 'balanced',
    mapCameraStyle: 'steady',
    mapFxIntensity: 'medium',
    depthFocus: 'subtle',
    gameplayCameraShake: 'full',
    menuParallax: 'off',
  },
  levelResults: {},
  upgrades: {
    ropeLength: 1,
    swingForce: 1,
    armor: 0,
    magnetism: 0,
    feverDuration: 0,
    luck: 0,
    launchBoost: 0,
    airControl: 0,
    safetyNet: 0,
    grip: 0,
    castRange: 0,
    branchMastery: 0,
    hazardResist: 0,
  },
};
export {
  BIOMES,
  BIOME_SCENE_PROFILES,
  GAME_ASSET_MANIFEST,
  HAZARD_BEHAVIOR_REGISTRY,
  INTRO_STORY_SEQUENCE,
  LEVELS,
  LEVEL_AUDIO_PROFILES,
  MAP_REGIONS,
  REWARD_PATTERN_REGISTRY,
  ROUTE_SCRIPTS,
  SHOP_ITEMS,
  THEME_PROFILES,
};
