import { LevelConfig } from '../types';

export const LEVELS: LevelConfig[] = [
  {
    id: 1,
    name: 'Elven Outskirts',
    description: 'The edge of the Kingdom.',
    targetDistance: 600,
    biome: 'JUNGLE',
    difficulty: 0,
    allowedEnemies: [],
    allowedWeather: ['CLEAR'],
    tutorialType: 'BASIC',
    checkpointCount: 1,
    actTemplates: ['recovery', 'reward', 'finale'],
    assetSetId: 'canopy-training',
    threatProfile: 'starter',
  },
  {
    id: 2,
    name: 'Royal Canopy',
    description: 'Deep in the Elven woods.',
    targetDistance: 1000,
    biome: 'JUNGLE',
    difficulty: 1,
    allowedEnemies: ['bird'],
    allowedWeather: ['CLEAR'],
    tutorialType: 'ADVANCED',
    checkpointCount: 1,
    actTemplates: ['recovery', 'speed', 'finale'],
    assetSetId: 'canopy-speed',
    threatProfile: 'canopy',
  },
  {
    id: 3,
    name: 'The Great Lake',
    description: 'Endless water below.',
    targetDistance: 1500,
    biome: 'SWAMP',
    difficulty: 3,
    allowedEnemies: ['bird', 'snake'],
    allowedWeather: ['CLEAR', 'RAIN'],
    tutorialType: 'NONE',
    checkpointCount: 2,
    actTemplates: ['recovery', 'reward', 'hazard'],
    assetSetId: 'wetlands-run',
    threatProfile: 'wetlands',
  },
  {
    id: 4,
    name: 'Misty Waters',
    description: 'Fog rolls over the lake.',
    targetDistance: 2000,
    biome: 'SWAMP',
    difficulty: 4,
    allowedEnemies: ['eagle', 'spider', 'crocodile', 'slug'],
    allowedWeather: ['FOG', 'RAIN'],
    tutorialType: 'NONE',
    checkpointCount: 2,
    actTemplates: ['recovery', 'hazard', 'finale'],
    assetSetId: 'fog-marsh',
    threatProfile: 'fog-marsh',
  },
  {
    id: 5,
    name: 'Troll Valley',
    description: 'Dark, damp, and dangerous.',
    targetDistance: 2500,
    biome: 'CAVE',
    difficulty: 5,
    allowedEnemies: ['spider', 'bat', 'troll'],
    allowedWeather: ['CLEAR'],
    tutorialType: 'NONE',
    checkpointCount: 2,
    actTemplates: ['recovery', 'hazard', 'finale'],
    assetSetId: 'cave-fork',
    threatProfile: 'cavern',
  },
  {
    id: 6,
    name: 'Lava Lake',
    description: 'The floor is literal lava.',
    targetDistance: 3000,
    biome: 'VOLCANO',
    difficulty: 6,
    allowedEnemies: ['bat', 'eagle'],
    allowedWeather: ['CLEAR', 'WINDY'],
    tutorialType: 'NONE',
    checkpointCount: 2,
    actTemplates: ['recovery', 'hazard', 'finale'],
    assetSetId: 'lava-lake',
    threatProfile: 'volcano',
  },
  {
    id: 7,
    name: 'Rocky Slopes',
    description: 'Steep climb.',
    targetDistance: 3500,
    biome: 'VOLCANO',
    difficulty: 7,
    allowedEnemies: ['eagle', 'spider'],
    allowedWeather: ['WINDY'],
    tutorialType: 'NONE',
    checkpointCount: 2,
    actTemplates: ['recovery', 'speed', 'finale'],
    assetSetId: 'volcano-ascent',
    threatProfile: 'volcano',
  },
  {
    id: 8,
    name: 'Ash Storm',
    description: 'Visibility low.',
    targetDistance: 4000,
    biome: 'VOLCANO',
    difficulty: 8,
    allowedEnemies: ['eagle', 'spider', 'bat'],
    allowedWeather: ['WINDY', 'FOG'],
    tutorialType: 'NONE',
    checkpointCount: 2,
    actTemplates: ['recovery', 'hazard', 'finale'],
    assetSetId: 'ash-storm',
    threatProfile: 'volcano',
  },
  {
    id: 9,
    name: 'The Peak',
    description: 'Almost there.',
    targetDistance: 4500,
    biome: 'VOLCANO',
    difficulty: 9,
    allowedEnemies: ['bird', 'spider', 'eagle', 'crocodile', 'bat'],
    allowedWeather: ['WINDY'],
    tutorialType: 'NONE',
    checkpointCount: 2,
    actTemplates: ['recovery', 'speed', 'finale'],
    assetSetId: 'summit-climb',
    threatProfile: 'volcano',
  },
  {
    id: 10,
    name: 'Magma Core',
    description: 'The final test.',
    targetDistance: 5000,
    biome: 'VOLCANO',
    difficulty: 10,
    allowedEnemies: ['bird', 'spider', 'eagle', 'bat', 'snake', 'troll'],
    allowedWeather: ['RAIN', 'WINDY', 'FOG'],
    tutorialType: 'NONE',
    checkpointCount: 2,
    actTemplates: ['recovery', 'hazard', 'finale'],
    assetSetId: 'magma-core',
    threatProfile: 'volcano',
  },
  {
    id: 11,
    name: 'Sky Bastion',
    description: 'Air routes above the ashline.',
    targetDistance: 5600,
    biome: 'VOLCANO',
    difficulty: 11,
    allowedEnemies: ['eagle', 'bird', 'bat', 'spider'],
    allowedWeather: ['WINDY', 'FOG'],
    tutorialType: 'NONE',
    checkpointCount: 3,
    actTemplates: ['recovery', 'reward', 'speed', 'hazard', 'finale'],
    assetSetId: 'magma-core',
    threatProfile: 'volcano',
  },
  {
    id: 12,
    name: 'Storm Crown',
    description: 'The final crownline above the ash.',
    targetDistance: 6200,
    biome: 'VOLCANO',
    difficulty: 12,
    allowedEnemies: ['bird', 'eagle', 'bat', 'spider', 'troll', 'snake'],
    allowedWeather: ['CLEAR', 'WINDY', 'RAIN', 'FOG'],
    tutorialType: 'NONE',
    checkpointCount: 3,
    actTemplates: ['recovery', 'reward', 'speed', 'hazard', 'finale'],
    assetSetId: 'magma-core',
    threatProfile: 'volcano',
  },
  {
    id: 13,
    name: 'Aether Bastion',
    description: 'Sky roads where the wind makes every line count.',
    targetDistance: 7000,
    biome: 'VOLCANO',
    difficulty: 13,
    allowedEnemies: ['bird', 'eagle', 'bat', 'spider', 'troll', 'snake'],
    allowedWeather: ['WINDY', 'FOG', 'RAIN'],
    tutorialType: 'NONE',
    checkpointCount: 4,
    actTemplates: ['recovery', 'reward', 'speed', 'hazard', 'finale'],
    assetSetId: 'magma-core',
    threatProfile: 'volcano',
  },
];
