import {
  Activity,
  Anchor,
  Brain,
  Crosshair,
  Feather,
  Gem,
  Ghost,
  Grab,
  Hammer,
  LifeBuoy,
  Move,
  Shield,
  Snowflake,
  Sparkles,
  Sprout,
  Zap,
} from 'lucide-react';

import { ShopItem } from '../types';

export const SHOP_ITEMS: ShopItem[] = [
  { id: 'rope_vine', name: 'Classic Vine', type: 'ROPE', cost: 0, description: 'The baseline rope line.', presentationGroup: 'Rope Types', visualEffectText: 'Balanced sag, balanced grip, and the cleanest all-around read.', synergyText: 'The default rope. Reliable anywhere.', routeHelpTags: ['Balanced', 'Starter'], ropeType: 'vine', icon: Anchor },
  { id: 'rope_braid', name: 'Braided Vine', type: 'ROPE', cost: 160, description: 'Tighter control and cleaner arcs.', presentationGroup: 'Rope Types', visualEffectText: 'Adds a braided weave and a slightly snappier swing profile.', synergyText: 'Pairs with Grip for cleaner retargets and longer hangs.', routeHelpTags: ['Control', 'Recovery'], ropeType: 'braid', icon: Move },
  { id: 'rope_chain', name: 'Iron Chain', type: 'ROPE', cost: 320, description: 'Heavy, stable, and hard to snap.', presentationGroup: 'Rope Types', visualEffectText: 'Swaps the rope to a darker chain line with stronger stress glow.', synergyText: 'Pairs with Armor and Hazard Resist for tough routes.', routeHelpTags: ['Caves', 'Volcano'], ropeType: 'chain', icon: Shield },
  { id: 'rope_silk', name: 'Silk Thread', type: 'ROPE', cost: 420, description: 'Long, smooth, and very forgiving.', presentationGroup: 'Rope Types', visualEffectText: 'Turns the rope into a luminous silk tether with soft trailing light.', synergyText: 'Pairs with Cast Range for huge recovery windows.', routeHelpTags: ['Speed', 'Late saves'], ropeType: 'silk', icon: Feather },
  { id: 'upgrade_rope', name: 'Vine Weaver', type: 'UPGRADE', cost: 50, description: 'Longer vines for deeper swings.', presentationGroup: 'Rope Control', visualEffectText: 'Adds a larger vine harness ring around the monkey.', synergyText: 'Pairs with Long Cast to widen retarget windows.', routeHelpTags: ['Jungle openers', 'Swamp recovery'], upgradeKey: 'ropeLength', maxLevel: 5, icon: Move, x: 50, y: 10 },
  { id: 'upgrade_force', name: 'Gorilla Strength', type: 'UPGRADE', cost: 75, description: 'Start swings with more power.', presentationGroup: 'Launch & Recovery', visualEffectText: 'Adds forearm wraps and a hotter launch posture.', synergyText: 'Pairs with Springy Tendons for faster exits.', routeHelpTags: ['Speed routes', 'Vertical launches'], upgradeKey: 'swingForce', maxLevel: 5, icon: Zap, x: 30, y: 30, parents: ['upgrade_rope'] },
  { id: 'upgrade_cast', name: 'Long Cast', type: 'UPGRADE', cost: 90, description: 'Reach wider anchors and easier recovery catches.', presentationGroup: 'Rope Control', visualEffectText: 'Projects a visible cast arc around the monkey.', synergyText: 'Pairs with Grip to make risky catches much safer.', routeHelpTags: ['Wide gaps', 'Late recoveries'], upgradeKey: 'castRange', maxLevel: 5, icon: Anchor, x: 70, y: 30, parents: ['upgrade_rope'] },
  { id: 'upgrade_magnet', name: 'Coin Magnet', type: 'UPGRADE', cost: 120, description: 'Attract coins nearby.', presentationGroup: 'Launch & Recovery', visualEffectText: 'Adds a red token magnet under the torso.', synergyText: 'Pairs with Lucky Clover for stronger token routes.', routeHelpTags: ['Reward routes', 'Token farming'], upgradeKey: 'magnetism', maxLevel: 5, icon: Crosshair, x: 20, y: 55, parents: ['upgrade_force'] },
  { id: 'upgrade_air', name: 'Aerodynamics', type: 'UPGRADE', cost: 120, description: 'Control movement mid-air.', presentationGroup: 'Launch & Recovery', visualEffectText: 'Adds wing-like fins for clearer air-control reads.', synergyText: 'Pairs with Long Cast to recover from awkward releases.', routeHelpTags: ['Wind routes', 'Rocky Slopes'], upgradeKey: 'airControl', maxLevel: 5, icon: Feather, x: 80, y: 55, parents: ['upgrade_cast'] },
  { id: 'upgrade_grip', name: 'Strong Grip', type: 'UPGRADE', cost: 140, description: 'Ropes hold longer and pump harder.', presentationGroup: 'Rope Control', visualEffectText: 'Adds bright hand wraps and thicker vine bindings.', synergyText: 'Long Cast + Grip makes retarget windows forgiving.', routeHelpTags: ['Cave forks', 'Long hangs'], upgradeKey: 'grip', maxLevel: 5, icon: Grab, x: 40, y: 75, parents: ['upgrade_force', 'upgrade_cast'] },
  { id: 'upgrade_focus', name: 'Focus Instinct', type: 'UPGRADE', cost: 120, description: 'Extends focus mode and recovery windows.', presentationGroup: 'Launch & Recovery', visualEffectText: 'Adds a pale focus halo above the head.', synergyText: 'Pairs with Air Control when routes get dense.', routeHelpTags: ['Hazard reads', 'Late saves'], upgradeKey: 'feverDuration', maxLevel: 5, icon: Brain, x: 60, y: 75, parents: ['upgrade_cast', 'upgrade_force'] },
  { id: 'upgrade_branch', name: 'Branch Mastery', type: 'UPGRADE', cost: 180, description: 'Branches hold longer when you reset on them.', presentationGroup: 'Rope Control', visualEffectText: 'Adds branch charms that flash during resets.', synergyText: 'Pairs with Armor for safer technical routes.', routeHelpTags: ['Branch lanes', 'Checkpoint saves'], upgradeKey: 'branchMastery', maxLevel: 5, icon: Hammer, x: 28, y: 95, parents: ['upgrade_grip'] },
  { id: 'upgrade_hazard', name: 'River Hide', type: 'UPGRADE', cost: 180, description: 'Reduce water drag, waterfall shove, and lava punishment.', presentationGroup: 'Survival & Utility', visualEffectText: 'Adds blue hazard wraps and a visible shield arc.', synergyText: 'Hazard Resist + Armor stabilizes cave and lava pushes.', routeHelpTags: ['Caves', 'Volcano', 'Water routes'], upgradeKey: 'hazardResist', maxLevel: 5, icon: LifeBuoy, x: 72, y: 95, parents: ['upgrade_air'] },
  { id: 'upgrade_launch', name: 'Springy Tendons', type: 'UPGRADE', cost: 220, description: 'Explosive speed when releasing.', presentationGroup: 'Launch & Recovery', visualEffectText: 'Adds ankle wraps and a stronger release flare.', synergyText: 'Pairs with Gorilla Strength to turn clean arcs into real launches.', routeHelpTags: ['Finale pushes', 'Speed clears'], upgradeKey: 'launchBoost', maxLevel: 5, icon: Sprout, x: 50, y: 112, parents: ['upgrade_grip', 'upgrade_air'] },
  { id: 'upgrade_armor', name: 'Coconut Helmet', type: 'UPGRADE', cost: 150, description: 'Survive one hit per run.', presentationGroup: 'Survival & Utility', visualEffectText: 'Adds a visible coconut helmet and shoulder pads.', synergyText: 'Pairs with Hazard Resist to keep bad lanes recoverable.', routeHelpTags: ['Caves', 'Ash Storm'], upgradeKey: 'armor', maxLevel: 3, icon: Shield, x: 18, y: 120, parents: ['upgrade_branch'] },
  { id: 'upgrade_luck', name: 'Lucky Clover', type: 'UPGRADE', cost: 200, description: 'Chance for double coins.', presentationGroup: 'Survival & Utility', visualEffectText: 'Adds clover charms that sparkle during pickups.', synergyText: 'Pairs with Coin Magnet to turn reward routes into real economy runs.', routeHelpTags: ['Reward routes', 'Endless value'], upgradeKey: 'luck', maxLevel: 5, icon: Sparkles, x: 82, y: 120, parents: ['upgrade_hazard', 'upgrade_magnet'] },
  { id: 'upgrade_net', name: 'Vine Net', type: 'UPGRADE', cost: 500, description: 'Bounce back from the void once.', presentationGroup: 'Survival & Utility', visualEffectText: 'Adds a visible net cradle behind the monkey.', synergyText: 'Pairs with Branch Mastery for forgiving checkpoint recoveries.', routeHelpTags: ['Long runs', 'Risk practice'], upgradeKey: 'safetyNet', maxLevel: 1, icon: LifeBuoy, x: 50, y: 138, parents: ['upgrade_launch'] },
  { id: 'skin_cyber', name: 'Cyber Kong', type: 'SKIN', cost: 500, description: 'Neon aesthetics.', presentationGroup: 'Cosmetics', visualEffectText: 'Recolors the monkey into a cyan neon scout.', synergyText: 'Pure style. No gameplay effect.', routeHelpTags: ['Style flex'], icon: Activity },
  { id: 'skin_winter', name: 'Yeti', type: 'SKIN', cost: 800, description: 'Cold resistance visual.', presentationGroup: 'Cosmetics', visualEffectText: 'Swaps the monkey palette to a cold mountain coat.', synergyText: 'Pure style. No gameplay effect.', routeHelpTags: ['Style flex'], icon: Snowflake },
  { id: 'skin_ninja', name: 'Ninja', type: 'SKIN', cost: 1200, description: 'Stealthy shadows.', presentationGroup: 'Cosmetics', visualEffectText: 'Shifts the silhouette into a darker stealth profile.', synergyText: 'Pure style. No gameplay effect.', routeHelpTags: ['Style flex'], icon: Ghost },
  { id: 'skin_golden', name: 'Golden God', type: 'SKIN', cost: 2500, description: 'Pure luxury.', presentationGroup: 'Cosmetics', visualEffectText: 'Turns the monkey into a bright gilded idol.', synergyText: 'Pure style. No gameplay effect.', routeHelpTags: ['Style flex'], icon: Gem },
];
