import { LevelAudioProfile, MapRegion, StorySequence } from '../types';

export const MAP_REGIONS: MapRegion[] = [
  {
    id: 'jungle-camp',
    label: 'Outer Canopy Camp',
    biome: 'JUNGLE',
    bounds: { x: 0, y: 500, width: 420, height: 340 },
    focalPoint: { x: 170, y: 665 },
    defaultZoom: 1.14,
    hazeColor: 'rgba(145, 220, 169, 0.18)',
    accentColor: '#7ef0c6',
    edgeShade: 0.24,
    artTokens: ['canopy', 'campfire', 'starter-lane'],
  },
  {
    id: 'floodline-rise',
    label: 'Floodline Rise',
    biome: 'JUNGLE',
    bounds: { x: 280, y: 360, width: 420, height: 290 },
    focalPoint: { x: 455, y: 545 },
    defaultZoom: 1.09,
    hazeColor: 'rgba(255, 228, 159, 0.16)',
    accentColor: '#f8d481',
    edgeShade: 0.2,
    artTokens: ['sunshafts', 'canopy-gap', 'reward-lane'],
  },
  {
    id: 'great-lake-basin',
    label: 'Great Lake Basin',
    biome: 'SWAMP',
    bounds: { x: 520, y: 280, width: 440, height: 320 },
    focalPoint: { x: 720, y: 470 },
    defaultZoom: 1.06,
    hazeColor: 'rgba(129, 205, 255, 0.2)',
    accentColor: '#7dd3fc',
    edgeShade: 0.22,
    artTokens: ['mist', 'water', 'reed-silhouette'],
  },
  {
    id: 'troll-valley',
    label: 'Troll Valley',
    biome: 'CAVE',
    bounds: { x: 860, y: 150, width: 380, height: 320 },
    focalPoint: { x: 1010, y: 335 },
    defaultZoom: 1.11,
    hazeColor: 'rgba(255, 188, 127, 0.15)',
    accentColor: '#f59e0b',
    edgeShade: 0.28,
    artTokens: ['cave-mouth', 'torch-glow', 'gate-lane'],
  },
  {
    id: 'magma-frontier',
    label: 'Magma Frontier',
    biome: 'VOLCANO',
    bounds: { x: 1160, y: 40, width: 400, height: 280 },
    focalPoint: { x: 1355, y: 190 },
    defaultZoom: 1.03,
    hazeColor: 'rgba(255, 126, 88, 0.19)',
    accentColor: '#fb923c',
    edgeShade: 0.3,
    artTokens: ['ash', 'lava-bloom', 'goal-spire'],
  },
  {
    id: 'storm-crown',
    label: 'Storm Crown',
    biome: 'VOLCANO',
    bounds: { x: 1240, y: -60, width: 320, height: 240 },
    focalPoint: { x: 1400, y: 130 },
    defaultZoom: 0.99,
    hazeColor: 'rgba(167, 139, 250, 0.2)',
    accentColor: '#a78bfa',
    edgeShade: 0.36,
    artTokens: ['gust', 'magma', 'aerial-fork'],
  },
  {
    id: 'aether-bastion',
    label: 'Aether Bastion',
    biome: 'VOLCANO',
    bounds: { x: 1600, y: -60, width: 300, height: 240 },
    focalPoint: { x: 1730, y: 90 },
    defaultZoom: 0.98,
    hazeColor: 'rgba(129, 199, 255, 0.22)',
    accentColor: '#67e8f9',
    edgeShade: 0.4,
    artTokens: ['aether-line', 'bastion-spire', 'gust'],
  },
];

export const INTRO_STORY_SEQUENCE: StorySequence = {
  id: 'forest-to-magma-intro',
  title: 'Forest To Magma',
  beats: [
    {
      id: 'camp-awakens',
      regionId: 'jungle-camp',
      title: 'Camp Wakes First',
      kicker: 'Issue 01',
      body:
        'The camp hears the magma core before it sees it.\nThe canopy is still safe here, but only barely.\nYour first clear pushes the rope line beyond the firelight.',
      hint: 'Level 1 is the first scouting swing.',
      visual: {
        scene: 'camp',
        speaker: 'Scout Nara',
        caption: 'Push the camp deeper before the ash reaches the roots.',
        accentWord: 'Scout',
        characterId: 'nara',
        supportCharacterId: 'ivo',
      },
      focusLevelId: 1,
      highlightLevelIds: [1],
      revealLevels: [1],
      revealScope: 'camp',
      voiceCueId: 'story_intro_camp',
      revealAction: 'focus_camp',
      cameraTarget: { x: 100, y: 670, zoom: 1.08 },
      cameraKeyframe: { x: 170, y: 665, zoom: 1.14, easing: 'easeOut', lingerMs: 700 },
    },
    {
      id: 'floodline',
      regionId: 'floodline-rise',
      title: 'Catch The Rhythm',
      kicker: 'Issue 02',
      body:
        'Floodline Rise is where the run starts to sing.\nCatch, drive, release, recover.\nIf the line feels smooth here, the rest of the map opens up.',
      hint: 'Click a node to inspect it. Double click or press Play to launch.',
      visual: {
        scene: 'floodline',
        speaker: 'Rope Chief Ivo',
        caption: 'Feel the arc first. Speed comes after.',
        accentWord: 'Swing',
        characterId: 'ivo',
        supportCharacterId: 'nara',
      },
      focusLevelId: 2,
      highlightLevelIds: [1, 2],
      revealLevels: [1, 2],
      revealScope: 'segment',
      voiceCueId: 'story_intro_waterline',
      revealAction: 'reveal_path',
      cameraTarget: { x: 455, y: 545, zoom: 1.09 },
      cameraKeyframe: { x: 455, y: 545, zoom: 1.09, easing: 'easeInOut', lingerMs: 950 },
    },
    {
      id: 'great-lake',
      regionId: 'great-lake-basin',
      title: 'Read The Water',
      kicker: 'Issue 03',
      body:
        'The basin splits every plan into choices.\nSafe lines keep the streak alive. Reward lines pay for the next leap.\nThe map starts judging how greedy you want to be.',
      hint: 'Each region holds multiple route tempos.',
      visual: {
        scene: 'basin',
        speaker: 'Quartermaster Pell',
        caption: 'Greed buys upgrades. Discipline keeps the run alive.',
        accentWord: 'Choice',
        characterId: 'pell',
        supportCharacterId: 'ivo',
      },
      focusLevelId: 4,
      highlightLevelIds: [3, 4],
      revealLevels: [1, 2, 3, 4],
      revealScope: 'region',
      voiceCueId: 'story_intro_basin',
      revealAction: 'highlight_route',
      cameraTarget: { x: 720, y: 470, zoom: 1.06 },
      cameraKeyframe: { x: 720, y: 470, zoom: 1.06, easing: 'easeInOut', lingerMs: 1100 },
    },
    {
      id: 'cave-warning',
      regionId: 'troll-valley',
      title: 'The Valley Bites Back',
      kicker: 'Issue 04',
      body:
        'Troll Valley is where sloppy reads get expensive.\nCaves narrow, hazards fake you out, and bad releases get punished.\nThere is still a safe line, but it never shouts.',
      hint: 'Threat icons show what hunts that route.',
      visual: {
        scene: 'cave',
        speaker: 'Trail Warden Suri',
        caption: 'If the route looks loud, the trap is already armed.',
        accentWord: 'Warning',
        characterId: 'suri',
        supportCharacterId: 'pell',
      },
      focusLevelId: 5,
      highlightLevelIds: [5, 6],
      revealLevels: [1, 2, 3, 4, 5, 6],
      revealScope: 'region',
      voiceCueId: 'story_intro_cave',
      revealAction: 'warn_biome',
      cameraTarget: { x: 1010, y: 335, zoom: 1.11 },
      cameraKeyframe: { x: 1010, y: 335, zoom: 1.11, easing: 'easeInOut', lingerMs: 1200 },
    },
    {
      id: 'magma-goal',
      regionId: 'magma-frontier',
      title: 'Race The Core',
      kicker: 'Issue 05',
      body:
        'Once the frontier glows, every upgrade matters.\nBank tokens, keep your chain alive, and carry momentum into the final push.\nAfter this page, the whole atlas belongs to you.',
      hint: 'After this, the full map is yours.',
      visual: {
        scene: 'magma',
        speaker: 'Camp Chorus',
        caption: 'Bring the whole loadout. The mountain is awake.',
        accentWord: 'Finale',
        characterId: 'chorus',
        supportCharacterId: 'suri',
      },
      focusLevelId: 11,
      highlightLevelIds: [7, 8, 9, 10, 11],
      revealLevels: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11],
      revealScope: 'full_route',
      voiceCueId: 'story_intro_core',
      revealAction: 'show_goal',
      cameraTarget: { x: 1355, y: 190, zoom: 1.03 },
      cameraKeyframe: { x: 1355, y: 190, zoom: 1.03, easing: 'easeInOut', lingerMs: 1400 },
    },
    {
      id: 'storm-crown',
      regionId: 'storm-crown',
      title: 'The Crown of Wind',
      kicker: 'Issue 06',
      body:
        'At the edge of the core the air folds into a crown.\nThere is no room for heavy routes, only clean arcs.\nThis is where momentum, discipline, and timing become one move.',
      hint: 'Treat every checkpoint as a rhythm gate—one precise hit opens the next branch.',
      visual: {
        scene: 'magma',
        speaker: 'Skywarden Lyra',
        caption: 'Do not chase the obvious line; steal the clean line.',
        accentWord: 'Crown',
        characterId: 'lyra',
        supportCharacterId: 'chorus',
      },
      focusLevelId: 12,
      highlightLevelIds: [11, 12],
      revealLevels: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
      revealScope: 'full_route',
      voiceCueId: 'story_intro_crown',
      revealAction: 'show_goal',
      cameraTarget: { x: 1400, y: 130, zoom: 0.98 },
      cameraKeyframe: { x: 1400, y: 130, zoom: 1.0, easing: 'easeOut', lingerMs: 1400 },
    },
    {
      id: 'aether-crest',
      regionId: 'aether-bastion',
      title: 'The Aether Crest',
      kicker: 'Issue 07',
      body:
        'Only the cleanest arc survives above the ashline.\nEvery branch reads like a weather map now: a single wrong rhythm can erase your momentum.\nPush a clean release and the whole clan can hold the highest route.',
      hint: 'Treat every checkpoint as a window, not a speed target.',
      visual: {
        scene: 'magma',
        speaker: 'Aster Kellan',
        caption: 'Read the wind, then cut the rope like a metronome.',
        accentWord: 'Clean',
        characterId: 'kellan',
        supportCharacterId: 'lyra',
      },
      focusLevelId: 13,
      highlightLevelIds: [12, 13],
      revealLevels: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13],
      revealScope: 'full_route',
      voiceCueId: 'story_intro_obelisk',
      revealAction: 'show_goal',
      cameraTarget: { x: 1730, y: 90, zoom: 0.98 },
      cameraKeyframe: { x: 1730, y: 90, zoom: 0.96, easing: 'easeInOut', lingerMs: 1500 },
    },
  ],
};

export const LEVEL_AUDIO_PROFILES: LevelAudioProfile[] = [
  { levelId: 1, musicCueId: 'music_jungle_route' },
  { levelId: 2, musicCueId: 'music_jungle_route' },
  { levelId: 3, musicCueId: 'music_swamp_route' },
  { levelId: 4, musicCueId: 'music_swamp_route' },
  { levelId: 5, musicCueId: 'music_cave_route' },
  { levelId: 6, musicCueId: 'music_volcano_route' },
  { levelId: 7, musicCueId: 'music_volcano_route' },
  { levelId: 8, musicCueId: 'music_volcano_route' },
  { levelId: 9, musicCueId: 'music_volcano_route' },
  { levelId: 10, musicCueId: 'music_core_route' },
  { levelId: 11, musicCueId: 'music_core_route' },
  { levelId: 12, musicCueId: 'music_core_route' },
  { levelId: 13, musicCueId: 'music_core_route' },
];
