import { LevelAudioProfile, MapRegion, StorySequence } from '../types';

export const MAP_REGIONS: MapRegion[] = [
  {
    id: 'jungle-camp',
    label: 'Outer Canopy Camp',
    biome: 'JUNGLE',
    bounds: { x: 0, y: 500, width: 420, height: 340 },
    focalPoint: { x: 170, y: 665 },
    defaultZoom: 1.14,
    hazeColor: 'rgba(145, 220, 169, 0.18)',
    accentColor: '#7ef0c6',
    edgeShade: 0.24,
    artTokens: ['canopy', 'campfire', 'starter-lane'],
  },
  {
    id: 'floodline-rise',
    label: 'Floodline Rise',
    biome: 'JUNGLE',
    bounds: { x: 280, y: 360, width: 420, height: 290 },
    focalPoint: { x: 455, y: 545 },
    defaultZoom: 1.09,
    hazeColor: 'rgba(255, 228, 159, 0.16)',
    accentColor: '#f8d481',
    edgeShade: 0.2,
    artTokens: ['sunshafts', 'canopy-gap', 'reward-lane'],
  },
  {
    id: 'great-lake-basin',
    label: 'Great Lake Basin',
    biome: 'SWAMP',
    bounds: { x: 520, y: 280, width: 440, height: 320 },
    focalPoint: { x: 720, y: 470 },
    defaultZoom: 1.06,
    hazeColor: 'rgba(129, 205, 255, 0.2)',
    accentColor: '#7dd3fc',
    edgeShade: 0.22,
    artTokens: ['mist', 'water', 'reed-silhouette'],
  },
  {
    id: 'troll-valley',
    label: 'Troll Valley',
    biome: 'CAVE',
    bounds: { x: 860, y: 150, width: 380, height: 320 },
    focalPoint: { x: 1010, y: 335 },
    defaultZoom: 1.11,
    hazeColor: 'rgba(255, 188, 127, 0.15)',
    accentColor: '#f59e0b',
    edgeShade: 0.28,
    artTokens: ['cave-mouth', 'torch-glow', 'gate-lane'],
  },
  {
    id: 'magma-frontier',
    label: 'Magma Frontier',
    biome: 'VOLCANO',
    bounds: { x: 1160, y: 40, width: 400, height: 280 },
    focalPoint: { x: 1355, y: 190 },
    defaultZoom: 1.03,
    hazeColor: 'rgba(255, 126, 88, 0.19)',
    accentColor: '#fb923c',
    edgeShade: 0.3,
    artTokens: ['ash', 'lava-bloom', 'goal-spire'],
  },
];

export const INTRO_STORY_SEQUENCE: StorySequence = {
  id: 'forest-to-magma-intro',
  title: 'Forest To Magma',
  beats: [
    {
      id: 'camp-awakens',
      regionId: 'jungle-camp',
      title: 'Start At Camp',
      body: 'This green node is home. Clear routes to push the camp deeper into the map.',
      hint: 'Level 1 is your opener.',
      focusLevelId: 1,
      highlightLevelIds: [1],
      revealLevels: [1],
      revealScope: 'camp',
      voiceCueId: 'story_intro_camp',
      revealAction: 'focus_camp',
      cameraTarget: { x: 100, y: 670, zoom: 1.08 },
      cameraKeyframe: { x: 170, y: 665, zoom: 1.14, easing: 'easeOut', lingerMs: 700 },
    },
    {
      id: 'floodline',
      regionId: 'floodline-rise',
      title: 'Learn The Swing',
      body: 'Early routes teach the loop: catch, drive, release, recover.',
      hint: 'Click a node to inspect it. Double click or press Play to launch.',
      focusLevelId: 2,
      highlightLevelIds: [1, 2],
      revealLevels: [1, 2],
      revealScope: 'segment',
      voiceCueId: 'story_intro_waterline',
      revealAction: 'reveal_path',
      cameraTarget: { x: 455, y: 545, zoom: 1.09 },
      cameraKeyframe: { x: 455, y: 545, zoom: 1.09, easing: 'easeInOut', lingerMs: 950 },
    },
    {
      id: 'great-lake',
      regionId: 'great-lake-basin',
      title: 'Read The Route',
      body: 'From here on, route choice matters. Safe lines protect the run. Reward lines feed the shop.',
      hint: 'Each region holds multiple routes.',
      focusLevelId: 4,
      highlightLevelIds: [3, 4],
      revealLevels: [1, 2, 3, 4],
      revealScope: 'region',
      voiceCueId: 'story_intro_basin',
      revealAction: 'highlight_route',
      cameraTarget: { x: 720, y: 470, zoom: 1.06 },
      cameraKeyframe: { x: 720, y: 470, zoom: 1.06, easing: 'easeInOut', lingerMs: 1100 },
    },
    {
      id: 'cave-warning',
      regionId: 'troll-valley',
      title: 'Midgame Turns Mean',
      body: 'Caves, trolls, gusts, and lava punish bad reads. There is still always one safe line.',
      hint: 'Threat icons show what lives on that route.',
      focusLevelId: 5,
      highlightLevelIds: [5, 6],
      revealLevels: [1, 2, 3, 4, 5, 6],
      revealScope: 'region',
      voiceCueId: 'story_intro_cave',
      revealAction: 'warn_biome',
      cameraTarget: { x: 1010, y: 335, zoom: 1.11 },
      cameraKeyframe: { x: 1010, y: 335, zoom: 1.11, easing: 'easeInOut', lingerMs: 1200 },
    },
    {
      id: 'magma-goal',
      regionId: 'magma-frontier',
      title: 'Push To The Core',
      body: 'Bank tokens, upgrade the loadout, and keep the chain alive all the way to magma.',
      hint: 'After this, the full map is yours.',
      focusLevelId: 10,
      highlightLevelIds: [7, 8, 9, 10],
      revealLevels: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
      revealScope: 'full_route',
      voiceCueId: 'story_intro_core',
      revealAction: 'show_goal',
      cameraTarget: { x: 1355, y: 190, zoom: 1.03 },
      cameraKeyframe: { x: 1355, y: 190, zoom: 1.03, easing: 'easeInOut', lingerMs: 1400 },
    },
  ],
};

export const LEVEL_AUDIO_PROFILES: LevelAudioProfile[] = [
  { levelId: 1, musicCueId: 'music_jungle_route' },
  { levelId: 2, musicCueId: 'music_jungle_route' },
  { levelId: 3, musicCueId: 'music_swamp_route' },
  { levelId: 4, musicCueId: 'music_swamp_route' },
  { levelId: 5, musicCueId: 'music_cave_route' },
  { levelId: 6, musicCueId: 'music_volcano_route' },
  { levelId: 7, musicCueId: 'music_volcano_route' },
  { levelId: 8, musicCueId: 'music_volcano_route' },
  { levelId: 9, musicCueId: 'music_volcano_route' },
  { levelId: 10, musicCueId: 'music_core_route' },
];
